### PR TITLE
fix for devices that dont have the scanner

### PR DESCRIPTION
**Pull request by sweebee**
Dont wait for init since devices that don't have the hardware scanner wont call device ready.

With this little fix it works fine, both on devices without a scanner and devices with a scanner.

### CODE REVIEW

**Comment by sweebee** [comment]
#3

**Comment by DanieleGiangrave** [comment]
Hello, could you help me to use this library?

**Comment by daguix** [comment]
Hey,

  Sorry it's too old and I don't possess the device anymore to debug the
code.

Best regards.

Le mer. 10 mars 2021 à 19:49, DanieleGiangrave ***@***.***> a
écrit :

**Comment by DanieleGiangrave** [comment]
Ok thank you
Do you know somebody That could help me? 😂

Il mer 10 mar 2021, 19:53 daguix <notifications@github.com> ha scritto:

**Pull request closed without merging**
